### ISSUE TITLE
Get final set of data for navigator.sendBeacon

### ISSUE THREAD

**Issue by ngbrown** [datalust/seq-logging#9]
When using seq-logging on a client side application, the flush doesn't work in `unload` or `pagehide` events.  The sequence of promises and waiting doesn't actually get waited for and the network event doesn't start.

An alternative is to get a final POST data and set up a `navigator.sendBeacon(url, data)`.  There is no opportunity to set headers, but setting the url to use `?apiKey=` should work.  I just need the data string out of the `SeqLogger` somehow.

What are your thoughts?

**Comment by nblumhardt** [comment]
Hi Nathan,

This sounds interesting - I can't see any reason it couldn't work :-)

There's going to still be the possibility that the timer in `SeqLogger` files just before unloading (so perhaps an in-flight batch might not complete?), but getting the contents of the log event queue as a string should be straightforward.

There's also the possibility that the batch will hit the (~64 kB) beacon size limit, but that would still be a big improvement on the status quo.

Perhaps it's worth a sanity check, by either hacking at the source, or accessing the "private" fields in `SeqLogger`? A production-quality API seems like it'll take a bit of thought, due to the browser-only nature of `sendBeacon()`, but it's definitely not insurmountable.

**Comment by nblumhardt** [comment]
Sounds like this should be covered by #10 - just catching back up on the backlog here, let me know if this is still an issue 👍
